export const FETCH_MENU = 'FETCH_MENU';
export const FETCH_MENU_SUCCESS = 'FETCH_MENU_SUCCESS';
export const FETCH_MENU_FAILURE = 'FETCH_MENU_FAILURE';
export const UPDATE_CART = 'UPDATE_CART';
export const EMPTY_CART = 'EMPTY_CART';
export const FETCH_TAXES = 'FETCH_TAXES';
export const FETCH_TAXES_SUCCESS = 'FETCH_TAXES_SUCCESS';
